### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by CarlWebster** [citrix/devdocs-issue-collector#113]
[Provide your feedback here]

Why are 2203/06/09/12 not listed in versions?

Citrix Virtual Apps and Desktops 2112 SDK Documentation
Versions
2112
2109
2103
2009
2006
1912
1811
1808

Docs URL:https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-sdk/en/2112/MachineCreation/about_ProvCustomProperties/

**Comment by katshann** [comment]
Hi Carl, the older versions of the SDK docs tend to be archived versions of the docs at the point hey were superseded. This includes the versions list - which is why it just has the older versions than the one you are currently looking at.  We are looking to change how we publish these docs in the future, which should get rid of this issue.  In the meantime, I'll have a look and see if I can do a manual fix. Cheers, Kat

**Comment by katshann** [comment]
I've updated the version selector in all of the 22xx releases to be more consistent. 
The 21xx and earlier releases are not as easy to update. So fixes to the version selector in these docs sets are not yet complete.

**Comment by katshann** [comment]
Hello,
The developer-docs have moved to a new platform (https://developer-docs.citrix.com/en-us/citrix-virtual-apps-desktops-sdk/current-release.html) and as a result feedback tickets for these docs will no longer be collected in this GitHub project. Accordingly, I shall close this ticket.
The new site has a better version selector and I think has solved this issue. 
Cheers,
Kat
