### ISSUE TITLE
Mandatory parameter

### ISSUE THREAD

**Issue by AtumVirt** [citrix/devdocs-issue-collector#14]
Please mark HostBaseUrl as mandatory in the cmdlet and docs.  This parameter is required for a 'default' (aka blank) install, which will be extremely common during official upgrade procedures.  Therefore, it makes sense to make it required all the time.  Also you could BOLD the note in description.

Docs URL:https://developer-docs.citrix.com/projects/storefront-powershell-sdk/en/latest/Import-STFConfiguration/

**Comment by davidgreen99** [comment]
@AtumVirt Thanks for the suggestion but our SMEs disagree. 
We should not mark it as Mandatory. **hostBaseUrl** parameter is not mandatory in all use cases.
We need this value in the following use cases, which are clearly mentioned in the Parameter section:

- HostBaseURL required if we want to change a different HostBaseURL other than the one contained in the configuration backup.
- HostBaseURL required if the customer importing onto a factory default Storefront installation. 

We also clearly describe in https://docs.citrix.com/en-us/storefront/1912-ltsr/export-import-storefront-config.html#powershell-cmdlets (edited): 

-HostBaseURL (String)If this parameter is included, the Host base URL you specify is used instead of the Host base URL from the exporting server.
Example: https://<importingserver>.example.com

**Comment by davidgreen99** [comment]
No defect.
