### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by CarlWebster** [citrix/devdocs-issue-collector#150]
[Provide your feedback here]

What permission is required to run this cmdlet? I am a CLoud Administrator. What else do I need?

PS C:\webster> get-vusschedule
get-vusschedule : Permission to perform the operation was denied.
At line:1 char:1
+ get-vusschedule
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (:) [Get-VusSchedule], UnauthorizedAccessException
    + FullyQualifiedErrorId : Citrix.XDPowerShell.Status.PermissionDenied,Citrix.VdaUpdateService.Sdk.Commands.GetVusScheduleCommand

BuiltIn          : False
Enabled          : True
IsCloudGroup     : False
IsHidden         : False
MetadataMap      : {}
Name             : Carl Webster (webster@carlwebster.com)
Rights           : {Cloud Administrator:All}
Sid              :
UserIdentity     : cas/user/611845554146616320
UserIdentityType : CitrixCloudIdentity

PS C:\webster> Get-AdminEffectiveRight |fl

RoleId    : 3a45035c-a260-4b4a-88a9-64461cba5acd
RoleName  : Cloud Administrator
ScopeId   : 00000000-0000-0000-0000-000000000000
ScopeName : All

Docs URL:https://developer-docs.citrix.com/projects/citrix-daas-sdk/en/latest/VdaUpdateService/Get-VusSchedule/

**Comment by katshann** [comment]
Hello,
I've passed on the question to the engineers. Depending on the answer, I'll hold of on raising a ticket for an SDK docs improvement in case this is a product issue.
Cheers,
Kat

**Comment by katshann** [comment]
Hello, 
As we discussed the other day, turns out this cmdlet isn't for customer use, but supposed to only be internal. The engineers are aware of the issue and have a ticket to remove this article
The developer-docs have moved to a new platform and as a result feedback tickets for these docs will no longer be collected in this GitHub project. Accordingly, I shall close this ticket and the related work will be tracked internally.
Cheers,
Kat
